### ISSUE TITLE
Conflicting Files

### ISSUE THREAD

**Issue by MisterBagel** [bijx/Zeus-Music-Mod-Generator#3]
Hello! Love your mod btw!

My problem is when I try to make two different music mods and run them at the same time via in-game Zeus, only one of them shows up instead of both. Is there a reason for this? If so is there any way I can avoid it so I can run two different music mods from the same program, aka yours.

**Comment by bijx** [comment]
Great question! Yes, the current version always uses the same class name by default since I was worried giving the option for customizing classnames would lead to some unforeseen errors in the code. But if you do want to use this for two different mods (before I get time to implement the custom class name feature), you can look at Captain Pepe's comment on my tutorial along with my subsequent reply! 

https://www.youtube.com/watch?v=Wmik02e1Arc

**Comment by bijx** [comment]
Oh okay, I just realized I already implemented this in ticket #1, but I haven't published a release yet. Will do that soon!

**Comment by MisterBagel** [comment]
Thanks man, your mod couldn't have come any sooner to help me out!

**Comment by MisterBagel** [comment]
So I tried what you suggested, it still doesn't come up.

Here is what I changed the class names with....

class CfgTest
{
	class CompanyofHeroes2
	{
		name = "Company of Heroes 2";
		author = "Your username";
		requiredVersion = 1.00;
		requiredAddons[] = {};
		units[] = {};
		weapons[] = {};
      	worlds[] = {};
	};
};
class CfgMusic
{
	#include "FileListWithMusicTracks.hpp"
};
class CfgTestClass
{
	class MyTestClass
	{
		displayName = "Company of Heroes 2";
	};
};








Here are the original class names........
class CfgPatches
{
	class CompanyofHeroes22
	{
		name = "Company of Heroes 22";
		author = "Your username";
		requiredVersion = 1.00;
		requiredAddons[] = {};
		units[] = {};
		weapons[] = {};
      	worlds[] = {};
	};
};
class CfgMusic
{
	#include "FileListWithMusicTracks.hpp"
};
class CfgMusicClasses
{
	class MyMusicClass
	{
		displayName = "Company of Heroes 22";
	};
};

**Comment by bijx** [comment]
Issue fixed in latest release.
